name: melodink_client
description: "Melodink, A self hosted Streaming Music Streaming App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.10.4'

hooks:
  user_defines:
    sqlite3:
      source: process

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  window_manager: ^0.5.1
  equatable: ^2.0.8
  audio_service: ^0.18.18
  rxdart: ^0.28.0
  mutex: ^3.1.0
  audio_service_mpris: ^0.2.0
  responsive_builder: ^0.7.1
  adwaita_icons:
    git:
      url: https://github.com/gungun974/adwaita_icons
      ref: 4506dba6301b6d9f969a93204b3642063f2d0316
  intl: ^0.20.2
  timeago: ^3.7.1
  sliver_tools: ^0.2.12
  audio_video_progress_bar: ^2.0.3
  flutter_svg: ^2.2.3
  cookie_jar: ^4.0.8
  flutter_hooks: ^0.21.3+1
  dio: ^5.9.0
  shared_preferences: ^2.5.4
  form_builder_validators: ^11.2.0
  dio_cookie_manager: ^3.3.0
  path_provider: ^2.1.5
  flutter_reorderable_list: ^1.3.1
  path: ^1.9.1
  connectivity_plus: ^7.0.0
  crypto: ^3.0.7
  logger: ^2.6.2
  color_thief_flutter:
    git:
      url: https://github.com/makromusic/color_thief_flutter
      ref: 951766094653f70655f8a5f4609c12f8e95db28b
  super_sliver_list: ^0.4.1
  flutter_switch: ^0.3.2
  dropdown_button2: ^2.3.9
  ffi: ^2.1.5
  uuid: ^4.5.2
  timeago_flutter: ^3.7.0
  popover: ^0.4.0
  omni_datetime_picker: ^2.3.1
  desktop_drop: ^0.7.0
  file_picker: ^10.3.8 
  file_saver: ^0.3.1
  slang: 4.10.0
  slang_flutter: 4.10.0
  duration: ^4.0.3
  flutter_rating_bar:
    git:
      url: https://github.com/gungun974/flutter_rating_bar
      ref: 098aad19d9147e2fa4b36ce6f9671a9b5d89d283
  audio_session: ^0.2.2
  diacritic: ^0.1.6
  flutter_cache_manager: ^3.4.1
  sqlite3: ^3.1.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  custom_lint: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/melodink_icon.png
    - assets/melodink_track_cover_not_found.png
    - assets/melodink_fulllogo.png

    - assets/icons/arrow-down.svg
    - assets/icons/arrow-left.svg
    - assets/icons/arrow-right.svg
    - assets/icons/download.svg
    - assets/icons/download2.svg
    - assets/icons/history-undo-symbolic.svg

    - lib/core/database/migrations/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/melodink_icon.png"
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/melodink_android_laucher_foreground.png" 
  min_sdk_android: 21
  web:
    generate: false
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true
